# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(831, 197)
        MainWindow.setMinimumSize(QtCore.QSize(800, 0))
        MainWindow.setMaximumSize(QtCore.QSize(850, 16777215))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.convertButton = QtWidgets.QPushButton(self.centralwidget)
        self.convertButton.setGeometry(QtCore.QRect(340, 90, 100, 40))
        self.convertButton.setMinimumSize(QtCore.QSize(100, 40))
        self.convertButton.setMaximumSize(QtCore.QSize(100, 40))
        self.convertButton.setObjectName("convertButton")
        self.widget = QtWidgets.QWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(20, 30, 791, 51))
        self.widget.setObjectName("widget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout.setSizeConstraint(QtWidgets.QLayout.SetMinimumSize)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setMinimumSize(QtCore.QSize(80, 30))
        self.label.setMaximumSize(QtCore.QSize(80, 30))
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.file_path = QtWidgets.QLineEdit(self.widget)
        self.file_path.setMinimumSize(QtCore.QSize(600, 30))
        self.file_path.setMaximumSize(QtCore.QSize(600, 30))
        self.file_path.setObjectName("file_path")
        self.horizontalLayout.addWidget(self.file_path)
        self.selectFileButton = QtWidgets.QPushButton(self.widget)
        self.selectFileButton.setMinimumSize(QtCore.QSize(60, 30))
        self.selectFileButton.setMaximumSize(QtCore.QSize(60, 30))
        self.selectFileButton.setObjectName("selectFileButton")
        self.horizontalLayout.addWidget(self.selectFileButton)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.selectFileButton.clicked.connect(MainWindow.select_file) # type: ignore
        self.convertButton.clicked.connect(MainWindow.convert_file) # type: ignore
        self.file_path.textChanged['QString'].connect(MainWindow.update_convert_button_text) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "PDF转换OFD文件"))
        self.convertButton.setText(_translate("MainWindow", "转换文件"))
        self.label.setText(_translate("MainWindow", "请选择文件："))
        self.selectFileButton.setText(_translate("MainWindow", "选择"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
